### ISSUE TITLE
Bug: TestClient used in pytest fails with `KeyError: 'session_maker_class'`

### ISSUE THREAD

**Issue by sherbang** [jolt-org/advanced-alchemy#147]
### Description

I've developed a failing test by writing a test that tries to test the litestar example in this repo:  https://github.com/jolt-org/advanced-alchemy/compare/main...sherbang:advanced-alchemy:litestar_test

### URL to code causing the issue

https://github.com/sherbang/advanced-alchemy/tree/litestar_test

### MCVE

```python
# Your MCVE code here
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

"In the format of: `![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)`"

### Logs

```bash
/home/sherbang/devel/advanced-alchemy/tests/examples/test_litestar.py::test_create failed: test_client = <litestar.testing.client.sync_client.TestClient object at 0x7582d98e9c50>

    async def test_create(test_client: TestClient[Litestar]) -> None:
        author = AuthorCreate(name="foo")
    
        response = test_client.post(
            "/authors",
            json=author.model_dump(mode="json"),
        )
>       assert response.status_code == 200, response.text
E       AssertionError: Traceback (most recent call last):
E           File "/home/sherbang/devel/advanced-alchemy/.venv/lib/python3.12/site-packages/litestar/middleware/exceptions/middleware.py", line 218, in __call__
E             await self.app(scope, receive, send)
E           File "/home/sherbang/devel/advanced-alchemy/.venv/lib/python3.12/site-packages/litestar/routes/http.py", line 82, in handle
E             response = await self._get_response_for_request(
E                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E           File "/home/sherbang/devel/advanced-alchemy/.venv/lib/python3.12/site-packages/litestar/routes/http.py", line 134, in _get_response_for_request
E             return await self._call_handler_function(
E                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E           File "/home/sherbang/devel/advanced-alchemy/.venv/lib/python3.12/site-packages/litestar/routes/http.py", line 154, in _call_handler_function
E             response_data, cleanup_group = await self._get_response_data(
E                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E           File "/home/sherbang/devel/advanced-alchemy/.venv/lib/python3.12/site-packages/litestar/routes/http.py", line 191, in _get_response_data
E             cleanup_group = await parameter_model.resolve_dependencies(request, kwargs)
E                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E           File "/home/sherbang/devel/advanced-alchemy/.venv/lib/python3.12/site-packages/litestar/_kwargs/kwargs_model.py", line 394, in resolve_dependencies
E             await resolve_dependency(next(iter(batch)), connection, kwargs, cleanup_group)
E           File "/home/sherbang/devel/advanced-alchemy/.venv/lib/python3.12/site-packages/litestar/_kwargs/dependencies.py", line 65, in resolve_dependency
E             value = await dependency.provide(**dependency_kwargs)
E                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E           File "/home/sherbang/devel/advanced-alchemy/.venv/lib/python3.12/site-packages/litestar/di.py", line 101, in __call__
E             value = self.dependency(**kwargs)
E                     ^^^^^^^^^^^^^^^^^^^^^^^^^
E           File "/home/sherbang/devel/advanced-alchemy/advanced_alchemy/extensions/litestar/plugins/init/config/asyncio.py", line 193, in provide_session
E             session_maker = cast("Callable[[], AsyncSession]", state[self.session_maker_app_state_key])
E                                                                ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E           File "/home/sherbang/devel/advanced-alchemy/.venv/lib/python3.12/site-packages/litestar/datastructures/state.py", line 90, in __getitem__
E             return self._state[key]
E                    ~~~~~~~~~~~^^^^^
E         KeyError: 'session_maker_class'
E         
E       assert 500 == 200
E        +  where 500 = <Response [500 Internal Server Error]>.status_code

tests/examples/test_litestar.py:28: AssertionError
```

### Jolt Project Version

0.8.1

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by Alc-Alc** [comment]
Heya, I do not think this is a bug but rather an issue with how you are using the test client fixture.

https://github.com/sherbang/advanced-alchemy/blob/10a72168b3266a648fbf05f1cc289c411b3dab77/tests/examples/test_litestar.py#L15-L18

```py
@pytest.fixture()
def test_client() -> TestClient[Litestar]:
    app.debug = True
    return TestClient(app=app)
```

you are not using it via a context manager, this is an example for fastapi, but the same applies for litestar

https://github.com/jolt-org/advanced-alchemy/blob/c3dba026e5e3d68717a41565e8cb659ee46cd1e9/tests/unit/test_extensions/test_starlette.py#L29-L32

if you do not use it via the context manager the asgi events are not emitted, the key that it claims to be missing is only set when asgi events are sent

**Comment by Alc-Alc** [comment]
> I'll submit a PR against Litestar's documentation that shows examples of fixtures just like this.

thanks 😇 

> I will let other @jolt-org/maintainers and @jolt-org/members comment on that, I do not object to this 🙂

**Comment by cofin** [comment]
Hi - yes, it's definitely helpful.  More coverage is always good!

**Comment by sherbang** [comment]
Well, the Litestar docs weren't _wrong_, I was just not reading carefully enough.  Still, I opened this PR to improve them: https://github.com/litestar-org/litestar/pull/3258

I'll update my PR on this repo as well, but close this issue since it's not a real issue.  Thanks for the feedback!
